### ISSUE TITLE
"git clone http://git.savannah.gnu.org/r/gnulib.git" fails: Read from server failed: Cannot allocate memory

### ISSUE THREAD

**Issue by blueyed** [jech/polipo#57] opened 2015-03-06 15:59 UTC
Using polipo as `$http_proxy`, it fails to clone the following Git repo:

    % git clone http://git.savannah.gnu.org/r/gnulib.git
    Cloning into 'gnulib'...
    remote: Counting objects: 160407, done.
    remote: Compressing objects: 100% (24057/24057), done.
    error: RPC failed; result=18, HTTP code = 200 MiB | 3.47 MiB/s     
    fatal: The remote end hung up unexpectedly
    fatal: early EOF
    fatal: index-pack failed

The polipo log contains:

    Established listening socket on port 3128.
    Parsed URL http://git.savannah.gnu.org/r/gnulib.git/info/refs?service=git-upload-pack: rc=0, x=7, y=27
    Uncacheable object http://git.savannah.gnu.org/r/gnulib.git/info/refs?service=git-upload-pack (66)
    Parsed URL http://git.savannah.gnu.org/r/gnulib.git/git-upload-pack: rc=0, x=7, y=27
    Uncacheable object http://git.savannah.gnu.org/r/gnulib.git/git-upload-pack (66)
    Short on chunk memory -- attempting to punch holes in the middle of objects.
    Short on chunk memory -- attempting to punch holes in the middle of objects.
    Short on chunk memory -- attempting to punch holes in the middle of objects.
    Short on chunk memory -- attempting to punch holes in the middle of objects.
    Short on chunk memory -- attempting to punch holes in the middle of objects.
    Short on chunk memory -- attempting to punch holes in the middle of objects.
    Read from server failed: Cannot allocate memory

**Comment by jech** [comment] 2015-06-25 13:39
Duplicate of #19.

**Closed by jech** 2015-06-25 13:39 UTC
